CREATE DATABASE  "CRM_DB" WITH TEMPLATE = template0 ENCODING = 'UTF8' CONNECTION LIMIT = -1;
ALTER DATABASE "CRM_DB" OWNER TO "CRM_USER";

CREATE DATABASE  "BILLING_DB" WITH TEMPLATE = template0 ENCODING = 'UTF8' CONNECTION LIMIT = -1;
ALTER DATABASE "BILLING_DB" OWNER TO "BILLING_USER";

CREATE DATABASE  "ASSET_DB" WITH TEMPLATE = template0 ENCODING = 'UTF8' CONNECTION LIMIT = -1;
ALTER DATABASE "ASSET_DB" OWNER TO "ASSET_USER";

CREATE DATABASE  "TAR_CRM_DB" WITH TEMPLATE = template0 ENCODING = 'UTF8' CONNECTION LIMIT = -1;
ALTER DATABASE "TAR_CRM_DB" OWNER TO "TAR_CRM_USER";

CREATE DATABASE  "TAR_BILLING_DB" WITH TEMPLATE = template0 ENCODING = 'UTF8' CONNECTION LIMIT = -1;
ALTER DATABASE "TAR_BILLING_DB" OWNER TO "TAR_BILLING_USER";

CREATE DATABASE  "TAR_ASSET_DB" WITH TEMPLATE = template0 ENCODING = 'UTF8' CONNECTION LIMIT = -1;
ALTER DATABASE "TAR_ASSET_DB" OWNER TO "TAR_ASSET_USER";