insert into contract_ref_id (contract_ref_id, contract_description) values ('101', 'E-Car PAYG')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('102', 'All Unlimited')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('103', 'E-Scooter Yearly Subscription')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('104', 'Bike Yearly Subscription')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('105', 'Bike PAYG')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('106', 'E-Scooter PAYG')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('107', 'Bike Monthly Subscription')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('108', 'E-Scooter Monthly Subscription')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('109', 'E-Car Monthly Subscription')ON CONFLICT DO NOTHING;
insert into contract_ref_id (contract_ref_id, contract_description) values ('110', 'E-Car Monthly Subscription')ON CONFLICT DO NOTHING;
