insert into sample_job_title (JOB_TITLE) values ('ATM Machine Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Accountant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Actor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Actuary')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Adhesive Bonding Machine Tender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Adjudicator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Administrative Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Administrative Services Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Adult Education Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Advertising Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Advertising Sales Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Aerobics Instructor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Aerospace Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Aerospace Engineering Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Equipment Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Grader')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Inspector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Sciences Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Sorter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Agricultural Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Air Conditioning Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Air Conditioning Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Air Traffic Controller')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Aircraft Cargo Handling Supervisor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Aircraft Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Aircraft Service Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Airline Copilot')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Airline Pilot')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ambulance Dispatcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ambulance Driver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Amusement Machine Servicer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Anesthesiologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Animal Breeder')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Animal Control Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Animal Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Animal Trainer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Animator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Answering Service Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Anthropologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Apparel Patternmaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Apparel Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Arbitrator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Archeologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Architect')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Architectural Drafter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Architectural Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Archivist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Art Director')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Art Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Artist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Assembler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Astronomer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Athlete')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Athletic Trainer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Atmospheric Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Audio And Video Equipment Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Audio-Visual And Multimedia Collections Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Audiologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Auditor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Author')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Auto Damage Insurance Appraiser')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Automotive And Watercraft Service Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Automotive Glass Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Automotive Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Avionics Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Baggage Porter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bailiff')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Baker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Barback')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Barber')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bartender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Basic Education Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Behavioral Disorder Counselor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bellhop')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bench Carpenter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bicycle Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bill And Account Collector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Billing And Posting Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Biochemist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Biological Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Biomedical Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Biophysicist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Blaster')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Blending Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Blockmason')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Boiler Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Boilermaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bookkeeper')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Boring Machine Tool Tender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Brazer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Brickmason')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bridge And Lock Tender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Broadcast News Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Broadcast Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Brokerage Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Budget Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Building Inspector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Bus Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Butcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Buyer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cabinetmaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cafeteria Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cafeteria Cook')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Camera Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Camera Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cardiovascular Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cargo Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Carpenter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Carpet Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cartographer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cashier')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Caster')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ceiling Tile Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cellular Equipment Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cement Masonchanneling Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Chauffeur')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Checker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Chef')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Chemical Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Chemical Plant Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Chemist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Chemistry Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Chief Executive')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Child Social Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Childcare Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Chiropractor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Choreographer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Civil Drafter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Civil Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Civil Engineering Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Claims Adjuster')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Claims Examiner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Claims Investigator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cleaner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Clinical Laboratory Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Clinical Laboratory Technologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Clinical Psychologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Coating Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Coatroom Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Coil Finisher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Coil Taper')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Coil Winder')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Coin Machine Servicer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Commercial Diver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Commercial Pilot')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Commodities Sales Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Communications Equipment Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Communications Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Community Association Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Community Service Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Compensation And Benefits Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Compliance Officer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Composer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Computer Hardware Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Computer Network Architect')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Computer Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Computer Programmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Computer Science Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Computer Support Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Computer Systems Administrator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Computer Systems Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Concierge')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Conciliator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Concrete Finisher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Conservation Science Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Conservation Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Conservation Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Conservator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Construction Inspector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Construction Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Construction Painter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Construction Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Continuous Mining Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Convention Planner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Conveyor Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cook')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cooling Equipment Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Copy Marker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Correctional Officer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Correctional Treatment Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Correspondence Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Correspondent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cosmetologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cost Estimator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Costume Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Counseling Psychologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Counselor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Courier')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Court Reporter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Craft Artist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Crane Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Credit Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Credit Checker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Credit Counselor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Criminal Investigator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Criminal Justice Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Crossing Guard')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Curator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Custom Sewer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Customer Service Representative')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cutter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Cutting Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dancer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Data Entry Keyer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Database Administrator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Decorating Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Delivery Services Driver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Demonstrator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dental Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dental Hygienist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dental Laboratory Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dentist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Derrick Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Designer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Desktop Publisher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Detective')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Diagnostic Medical Sonographer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Die Maker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Diesel Engine Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dietetic Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dietitian')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dinkey Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Director')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dishwasher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dispatcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Door-To-Door Sales Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Drafter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dragline Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Drama Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dredge Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dressing Room Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dressmaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Drier Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Drilling Machine Tool Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dry-Cleaning Workerdrywall Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Dyeing Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Earth Driller')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Economics Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Economist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Editor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Education Administrator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Electric Motor Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Electrical Electronics Drafter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Electrical Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Electrical Equipment Assembler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Electrical Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Electrical Power-Line Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Electrician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Electro-Mechanical Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Elementary School Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Elevator Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Elevator Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Embalmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Emergency Management Director')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Emergency Medical Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Engine Assembler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Engineering Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Engineering Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('English Language Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Engraver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Entertainment Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Environmental Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Environmental Science Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Environmental Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Epidemiologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Escort')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Etcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Event Planner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Excavating Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Executive Administrative Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Executive Secretary')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Exhibit Designer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Expediting Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Explosives Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Extraction Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fabric Mender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fabric Patternmaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fabricator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Faller')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Family Practitioner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Family Social Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Family Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Farm Advisor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Farm Equipment Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Farm Labor Contractor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Farmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Farmworker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fashion Designer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fast Food Cook')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fence Erector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fiberglass Fabricator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fiberglass Laminator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('File Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Filling Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Film And Video Editor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Financial Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Financial Examiner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Financial Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Financial Services Sales Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fine Artist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fire Alarm System Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fire Dispatcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fire Inspector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fire Investigator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Firefighter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fish And Game Warden')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fish Cutter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fish Trimmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fisher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fitness Studies Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fitness Trainer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Flight Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Floor Finisher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Floor Layer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Floor Sander')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Floral Designer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Food Batchmaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Food Cooking Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Food Preparation Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Food Science Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Food Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Food Server')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Food Service Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Food Technologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Foreign Language Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Foreign Literature Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Forensic Science Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Forest Fire Inspector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Forest Fire Prevention Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Forest Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Forester')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Forestry Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Forging Machine Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Foundry Coremaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Freight Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Freight Mover')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Fundraising Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Funeral Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Funeral Director')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Funeral Service Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Furnace Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Furnishings Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Furniture Finisher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gaming Booth Cashier')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gaming Cage Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gaming Change Person')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gaming Dealer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gaming Investigator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gaming Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gaming Surveillance Officer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Garment Mender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Garment Presser')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gas Compressor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gas Plant Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gas Pumping Station Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('General Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('General Practitioner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Geographer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Geography Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Geological Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Geological Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Geoscientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Glazier')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Government Program Eligibility Interviewer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Graduate Teaching Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Graphic Designer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Groundskeeper')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Groundskeeping Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Gynecologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hairdresser')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hairstylist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hand Grinding Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hand Laborer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hand Packager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hand Packer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hand Polishing Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hand Sewer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hazardous Materials Removal Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Head Cook')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Health And Safety Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Health Educator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Health Information Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Health Services Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Health Specialties Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Healthcare Social Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hearing Officer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Heat Treating Equipment Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Heating Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Heating Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Heavy Truck Driver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Highway Maintenance Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Historian')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('History Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hoist And Winch Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Home Appliance Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Home Economics Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Home Entertainment Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Home Health Aide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Home Management Advisor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Host')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hostess')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hostler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hotel Desk Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Housekeeping Cleaner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Human Resources Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Human Resources Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Human Service Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hunter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Hydrologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Illustrator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Industrial Designer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Industrial Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Industrial Engineering Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Industrial Machinery Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Industrial Production Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Industrial Truck Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Industrial-Organizational Psychologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Information Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Information Research Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Information Security Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Information Systems Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Inspector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Instructional Coordinator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Instructor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Insulation Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Insurance Claims Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Insurance Sales Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Insurance Underwriter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Intercity Bus Driver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Interior Designer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Internist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Interpreter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Interviewer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Investigator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Jailer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Janitor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Jeweler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Judge')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Judicial Law Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Kettle Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Kiln Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Kindergarten Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Laboratory Animal Caretaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Landscape Architect')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Landscaping Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Lathe Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Laundry Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Law Enforcement Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Law Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Lawyer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Layout Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Leather Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Legal Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Legal Secretary')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Legislator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Librarian')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Library Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Library Science Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Library Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Licensed Practical Nurse')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Licensed Vocational Nurse')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Life Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Lifeguard')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Light Truck Driver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Line Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Literacy Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Literature Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Loading Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Loan Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Loan Interviewer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Loan Officer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Lobby Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Locker Room Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Locksmith')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Locomotive Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Locomotive Firer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Lodging Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Log Grader')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Logging Equipment Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Logistician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Machine Feeder')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Machinist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Magistrate')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Magistrate Judge')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Maid')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mail Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mail Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mail Superintendent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Maintenance Painter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Maintenance Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Makeup Artist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Management Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Manicurist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Manufactured Building Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mapping Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Marble Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Marine Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Marine Oiler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Market Research Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Marketing Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Marketing Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Marriage Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Massage Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Material Mover')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Materials Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Materials Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mathematical Science Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mathematical Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mathematician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Maxillofacial Surgeon')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Measurer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Meat Cutter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Meat Packer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Meat Trimmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mechanical Door Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mechanical Drafter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mechanical Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mechanical Engineering Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mediator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Appliance Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Equipment Preparer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Equipment Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Laboratory Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Laboratory Technologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Records Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Secretary')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Services Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Medical Transcriptionist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Meeting Planner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mental Health Counselor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mental Health Social Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Merchandise Displayer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Messenger')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Metal Caster')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Metal Patternmaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Metal Pickling Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Metal Pourer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Metal Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Metal-Refining Furnace Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Metal-Refining Furnace Tender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Meter Reader')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Microbiologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Middle School Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Milling Machine Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Millwright')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mine Cutting Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mine Shuttle Car Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mining Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mining Safety Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mining Safety Inspector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mining Service Unit Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mixing Machine Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mobile Heavy Equipment Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mobile Home Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Model')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Model Maker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Molder')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Mortician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Motel Desk Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Motion Picture Projectionist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Motorboat Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Motorboat Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Motorboat Service Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Motorcycle Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Multimedia Artist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Museum Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Music Director')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Music Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Musical Instrument Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Musician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Natural Sciences Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Naval Architect')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Network Systems Administrator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('New Accounts Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('News Vendor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nonfarm Animal Caretaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nuclear Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nuclear Medicine Technologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nuclear Power Reactor Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nuclear Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nursing Aide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nursing Instructor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nursing Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Nutritionist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Obstetrician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Occupational Health And Safety Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Occupational Health And Safety Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Occupational Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Occupational Therapy Aide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Occupational Therapy Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Offbearer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Office Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Office Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Operating Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Operations Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Operations Research Analyst')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ophthalmic Laboratory Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Optician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Optometrist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Oral Surgeon')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Order Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Order Filler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Orderly')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ordnance Handling Expert')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Orthodontist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Orthotist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Outdoor Power Equipment Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Oven Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Packaging Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Painter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Painting Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Paper Goods Machine Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Paperhanger')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Paralegal')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Paramedic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Parking Enforcement Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Parking Lot Attendant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Parts Salesperson')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Paving Equipment Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Payroll Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pediatrician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pedicurist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Personal Care Aide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Personal Chef')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Personal Financial Advisor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pest Control Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pesticide Applicator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pesticide Handler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pesticide Sprayer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Petroleum Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Petroleum Gauger')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Petroleum Pump System Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Petroleum Refinery Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Petroleum Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pharmacist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pharmacy Aide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pharmacy Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Philosophy Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Photogrammetrist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Photographer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Photographic Process Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Photographic Processing Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Physical Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Physical Therapist Aide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Physical Therapist Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Physician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Physician Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Physicistphysics Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pile-Driver Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pipefitter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pipelayer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Planing Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Planning Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Plant Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Plant Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Plasterer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Plastic Patternmaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Plastic Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Plumber')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Podiatrist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Police Dispatcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Police Officer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Policy Processing Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Political Science Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Political Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Postal Service Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Postal Service Mail Carrier')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Postal Service Mail Processing Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Postal Service Mail Processor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Postal Service Mail Sorter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Postmaster')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Postsecondary Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Poultry Cutter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Poultry Trimmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Power Dispatcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Power Distributor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Power Plant Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Power Tool Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Precious Stone Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Precision Instrument Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Prepress Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Preschool Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Priest')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Print Binding Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Printing Press Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Private Detective')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Probation Officer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Procurement Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Producer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Product Promoter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Production Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Production Occupation')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Proofreader')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Property Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Prosthetist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Prosthodontist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Psychiatric Aide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Psychiatric Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Psychiatrist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Psychologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Psychology Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Public Relations Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Public Relations Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Pump Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Purchasing Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Purchasing Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Radiation Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Radio Announcer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Radio Equipment Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Radio Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Radiologic Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Radiologic Technologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rail Car Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rail Transportation Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rail Yard Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rail-Track Laying Equipment Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Railroad Brake Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Railroad Conductor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Railroad Police')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rancher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Real Estate Appraiser')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Real Estate Broker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Real Estate Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Real Estate Sales Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Receiving Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Receptionist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Record Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Recreation Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Recreation Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Recreational Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Recreational Vehicle Service Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Recyclable Material Collector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Referee')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Refractory Materials Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Refrigeration Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Refrigeration Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Refuse Collector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Regional Planner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Registered Nurse')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rehabilitation Counselor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Reinforcing Iron Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Reinforcing Rebar Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Religion Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Religious Activities Director')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Religious Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rental Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Repair Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Reporter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Residential Advisor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Resort Desk Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Respiratory Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Respiratory Therapy Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Retail Buyer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Retail Salesperson')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Revenue Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rigger')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rock Splitter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rolling Machine Tender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Roof Bolter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Roofer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Rotary Drill Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Roustabout')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Safe Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sailor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sales Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sales Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sales Representative')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sampler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sawing Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Scaler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('School Bus Driver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('School Psychologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('School Social Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Scout Leader')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sculptor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Secondary Education Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Secondary School Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Secretary')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Securities Sales Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Security Guard')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Security System Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Segmental Paver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Self-Enrichment Education Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Semiconductor Processor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Septic Tank Servicer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Set Designer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sewer Pipe Cleaner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sewing Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Shampooer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Shaper')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sheet Metal Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sheriff Patrol Officer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ship Captain')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ship Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ship Loader')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Shipmate')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Shipping Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Shoe Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Shoe Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Short Order Cook')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Signal Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Signal Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Singer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ski Patrol')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Skincare Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Slaughterer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Slicing Machine Tender')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Slot Supervisor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Social Science Research Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Social Sciences Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Social Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Social Service Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Social Service Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Social Work Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Social Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sociologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sociology Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Software Developer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Software Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Soil Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Solderer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sorter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sound Engineering Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Space Scientist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Special Education Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Speech-Language Pathologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sports Book Runner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sports Entertainer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Sports Performer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Stationary Engineer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Statistical Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Statistician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Steamfitter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Stock Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Stock Mover')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Stonemason')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Street Vendor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Streetcar Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Structural Iron Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Structural Metal Fabricator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Structural Metal Fitter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Structural Steel Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Stucco Mason')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Substance Abuse Counselor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Substance Abuse Social Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Subway Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Surfacing Equipment Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Surgeon')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Surgical Technologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Survey Researcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Surveying Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Surveyor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Switch Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Switchboard Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tailor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tamping Equipment Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tank Car Loader')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Taper')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tax Collector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tax Examiner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tax Preparer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Taxi Driver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Teacher Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Team Assembler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Technical Writer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Telecommunications Equipment Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Telemarketer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Telephone Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Television Announcer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Teller')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Terrazzo Finisher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Terrazzo Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tester')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Textile Bleaching Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Textile Cutting Machine Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Textile Knitting Machine Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Textile Presser')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Textile Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Therapist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ticket Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Ticket Taker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tile Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Timekeeping Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Timing Device Assembler')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tire Builder')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tire Changertire Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Title Abstractor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Title Examiner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Title Searcher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tobacco Roasting Machine Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tool Filer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tool Grinder')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tool Maker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tool Sharpener')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tour Guide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tower Equipment Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tower Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Track Switch Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tractor Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tractor-Trailer Truck Driver')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Traffic Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Traffic Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Training And Development Manager')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Training And Development Specialist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Transit Police')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Translator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Transportation Equipment Painter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Transportation Inspector')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Transportation Security Screener')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Transportation Worker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Trapper')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Travel Agent')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Travel Clerk')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Travel Guide')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tree Pruner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tree Trimmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Trimmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Truck Loader')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Truck Mechanic')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Tuner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Turning Machine Tool Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Typist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Umpire')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Undertaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Upholsterer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Urban Planner')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Usher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Valve Installer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Vending Machine Servicer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Veterinarian')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Veterinary Assistant')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Veterinary Technician')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Vocational Counselor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Vocational Education Teacher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Waiter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Waitress')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Watch Repairer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Water Treatment Plant Operator')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Weaving Machine Setter')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Web Developer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Weigher')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Welder')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Wellhead Pumper')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Wholesale Buyer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Wildlife Biologist')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Window Trimmer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Wood Patternmaker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Woodworker')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Word Processor')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Writer')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Yardmaster')ON CONFLICT DO NOTHING;
insert into sample_job_title (JOB_TITLE) values ('Zoologist')ON CONFLICT DO NOTHING;
