insert into sample_postal_codes (zip_code, city, state) values ('75201', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75202', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75203', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75204', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75205', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75206', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75207', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75208', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75209', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75210', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75211', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75212', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75214', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75215', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75216', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75217', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75218', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75219', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75220', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75221', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75222', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75223', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75224', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75225', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75226', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75227', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75228', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75229', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75230', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75231', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75232', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75233', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('75234', 'Dallas', 'TX' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90001', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90002', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90003', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90004', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90005', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90006', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90007', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90008', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90009', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90010', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90011', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90012', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90013', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90014', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90015', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90016', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90017', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90018', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90019', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90020', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90021', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90022', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90023', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90024', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90025', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90026', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90027', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90028', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90029', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90030', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90031', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90032', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90033', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90034', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90035', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90036', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90037', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90038', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90039', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90040', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90041', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90042', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90043', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90044', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90045', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90046', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90047', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90048', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90049', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90050', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90051', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90052', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90053', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90054', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90055', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90056', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90057', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90058', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90059', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('90060', 'Los Angeles', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60601', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60602', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60603', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60604', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60605', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60606', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60607', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60608', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60609', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60610', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60611', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60612', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60613', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60614', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60615', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60616', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60617', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60618', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60619', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60620', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60621', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60622', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60623', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60624', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60625', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60626', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60628', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60629', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60630', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60631', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60632', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60633', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60634', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60636', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60637', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60638', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60639', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60640', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60641', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60642', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60643', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60644', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60645', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60646', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60647', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60649', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60651', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60652', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60653', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60654', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60655', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60656', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60657', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60659', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('60660', 'Chicago', 'IL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10001', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10002', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10003', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10004', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10005', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10006', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10007', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10008', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10009', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10010', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10011', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10012', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10013', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10014', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10015', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10016', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10017', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10018', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10019', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10020', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10021', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10022', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10023', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10024', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10025', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10026', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10027', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10028', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10029', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10030', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10031', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10032', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10033', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10034', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10035', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10036', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10037', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10038', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10039', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10040', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10041', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10044', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10045', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10048', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10055', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10069', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10090', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10098', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('10099', 'New York', 'NY' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92101', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92102', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92103', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92104', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92105', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92106', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92107', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92108', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92109', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92110', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92111', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92112', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92113', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92114', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92115', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92116', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92117', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92119', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92120', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92121', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92122', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92123', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92124', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92126', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92127', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92128', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92129', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92130', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92131', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92132', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92134', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92135', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92136', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92137', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92138', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92139', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92140', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92142', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92145', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92147', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92149', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92150', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92152', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92153', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92154', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92155', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92158', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92159', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92160', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92161', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92163', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92165', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92166', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92167', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('92168', 'San Diego', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33116', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33119', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33122', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33124', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33125', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33126', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33127', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33128', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33129', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33130', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33131', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33132', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33133', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33134', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33135', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33136', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33137', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33138', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33140', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33141', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33142', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33143', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33144', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33145', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33146', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33147', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33149', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33150', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33151', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33152', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33153', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33154', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33155', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33156', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33157', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33158', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33160', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33161', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33162', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33163', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33164', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33165', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33166', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33167', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33168', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33169', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33170', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33172', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33173', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33174', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33175', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33176', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33177', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33178', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33179', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('33180', 'Miami', 'FL' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98101', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98102', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98103', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98104', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98105', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98106', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98107', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98108', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98109', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98112', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98115', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98116', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98117', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98118', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98119', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98121', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98122', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98125', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98126', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98133', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98134', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98136', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98144', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98154', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98164', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98174', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('98199', 'Seattle', 'WA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94103', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94104', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94105', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94107', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94108', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94109', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94110', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94111', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94112', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94114', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94115', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94116', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94117', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94118', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94119', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94120', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94121', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94122', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94123', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94124', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94125', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94126', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94127', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94128', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94129', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94130', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94131', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94132', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94133', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94134', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94137', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94139', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94140', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94141', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94142', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94143', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94144', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94145', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94146', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94147', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94151', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94158', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94159', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94160', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94161', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94163', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94164', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94172', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94177', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
insert into sample_postal_codes (zip_code, city, state) values ('94188', 'San Francisco', 'CA' )ON CONFLICT DO NOTHING;
