INSERT INTO public.tmp_roles(rolname) VALUES ('CRM_USER')ON CONFLICT DO NOTHING;
INSERT INTO public.tmp_roles(rolname) VALUES ('BILLING_USER')ON CONFLICT DO NOTHING;
INSERT INTO public.tmp_roles(rolname) VALUES ('ASSET_USER')ON CONFLICT DO NOTHING;
INSERT INTO public.tmp_roles(rolname) VALUES ('TAR_CRM_USER')ON CONFLICT DO NOTHING;
INSERT INTO public.tmp_roles(rolname) VALUES ('TAR_BILLING_USER')ON CONFLICT DO NOTHING;
INSERT INTO public.tmp_roles(rolname) VALUES ('TAR_ASSET_USER')ON CONFLICT DO NOTHING;